# These are all the cops that are disabled in the default configuration.

Style/LineLength:
  Enabled: false

Style/MethodLength:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/InlineComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false
